version: "3"
services:
  traefik:
    image: "traefik:v2.0"
    volumes:
      - /home/data/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443
  whoami:
    image: "containous/whoami"
    